/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertorialRouteImport } from './routes/advertorial'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertorialRoute = AdvertorialRouteImport.update({
  id: '/advertorial',
  path: '/advertorial',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertorial': typeof AdvertorialRoute
  '/order-complete': typeof OrderCompleteRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertorial': typeof AdvertorialRoute
  '/order-complete': typeof OrderCompleteRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertorial': typeof AdvertorialRoute
  '/order-complete': typeof OrderCompleteRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertorial'
    | '/order-complete'
    | '/checkout/$planId'
    | '/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertorial'
    | '/order-complete'
    | '/checkout/$planId'
    | '/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/advertorial'
    | '/order-complete'
    | '/checkout/$planId'
    | '/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertorialRoute: typeof AdvertorialRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertorial': {
      id: '/advertorial'
      path: '/advertorial'
      fullPath: '/advertorial'
      preLoaderRoute: typeof AdvertorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertorialRoute: AdvertorialRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  ProductsHandleRoute: ProductsHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
